### PR TITLE
Display comments pop up with selected items details 

### PR DESCRIPTION
**Pull request by learnwithalfred**
## Pop up menu done 

All changes done

https://user-images.githubusercontent.com/34389326/174916556-660c4324-5a36-48e7-a3bf-8e7cc860908f.mp4

### CODE REVIEW

**Comment by GiuseppeTG** [comment]
Hello @learnwithalfred  👋 

Good job! The pop-up window is working well. 

I think that for now, you are implementing mocked data into your pop-up window not related to the TVmaze API. It would be better to know what kind of information we should display on the window to organize the UI better. 

The comments should be displayed when you submit them.

I also noticed in the video that the comment text area has the resize, I think it would be better to let it be of a fixed value. 

Keep up the good work, congratulations!

**Review by GiuseppeTG — COMMENTED** [review]
Hello @learnwithalfred 👋 

The pop-up window works correctly. Good job!

You are ready to merge it.

**Review by GiuseppeTG — APPROVED** [review]

**Comment by learnwithalfred** [comment]
Thanks the recommendation

**Comment by learnwithalfred** [comment]
Thank you for the nice message

**Pull request merged**
